name = "Layla"

homepage = "https://layla.dev"

min_version = "0.67.3 Extended"
tags = ["appearances","tips","streams","video",]
features = ["font-awesome","favicon","one-page","responsive","sass","scss"]

license = "Creative Commons"
licenselink = "https://github.com/caressofsteel/hugo-story/blob/master/LICENSE"


baseURL = "https://layla.dev"
title = "Layla"
languageCode= "en-us"
defaultContentLanguage= "en"
theme = "hugo-story"
summaryLength = 25
copyright = "Layla - All rights reserved"
enableEmoji = true
publishDir = "public"
#googleAnalytics = "UA-1XXXXXXX1-1"

[params]
  logo = "/images/logo.png"
  hello = "Hello! I'm Layla"
  description ="I'm a developer advocate, live coder, international speaker, Microsoft MVP, and a GitHub Star."
 


[params.index]
  picture = "/images/layla-self.jpg"
  title = "Hello! I'm Layla"
  subtitle = "I'm a developer advocate, live coder, international speaker, Microsoft MVP, and a GitHub Star."
  alertbar = false

[params.social]
  github = "Layla-p"
  linkedin = "layla-porter"
  twitter = "laylacodesit"
  twitch = "laylacodesit"
  tiktok = "laylacodesit"






