baseURL = 'https://layla.dev/'
languageCode = 'en-us'
title = 'LaylaCodesIt'


[markup]
  defaultMarkdownHandler = "goldmark"


min_version = "0.67.3 Extended"

[params]
  description = "Layla's personal site wand the home of the Hooked on .NET newsletter."
  images = ["images/youtube.png"]
  newsletter = "/:section/:slug/"

    [params.social]
    twitter = 'LaylaCodesIt'
    images = ['images/youtube.png']

  [[params.navlinks]]
    name = "Newsletter"
    url = "hooked-on-dotnet/"

  [[params.navlinks]]
    name = "Workshops"
    url = "workshops/"

  [[params.navlinks]]
    name = "Talks"
    url = "talks/"

  [[params.navlinks]]
    name = "Appearances"
    url = "appearances/"

  [[params.navlinks]]
    name = "Guest"
    url = "guest/"

  [[params.navlinks]]
    name = "Contact"
    url = "contact/"